In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import os
import cv2

# 1.Tien Xu Ly Anh

In [2]:
# Doc anh tu thu muc
data_path = "/home/nguyenngocduong/Desktop/face_recognition_project/data"
images = []
labels = []
for person_name in sorted(os.listdir(data_path)):
    person_folder = os.path.join(data_path, person_name)
    if os.path.isdir(person_folder):
        for image in sorted(os.listdir(person_folder)):
            image_path = os.path.join(person_folder, image)
            img = cv2.imread(image_path)
            if img is None:
                continue
            images.append(img)
            labels.append(person_name)
print(f"Tổng số ảnh: {len(images)}")
print(f"Số class: {len(set(labels))}")

Tổng số ảnh: 162
Số class: 9


In [11]:
cv2.imshow("Sample Image", images[0])
cv2.waitKey(0)
cv2.destroyAllWindows()

# Áp dụng Face Detection để lấy gương mặt

In [3]:
from mtcnn import MTCNN
#detect truoc roi moi resize anh
detector = MTCNN()
faces_data = []
labels_data = []
for image, label in zip(images, labels):
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    faces = detector.detect_faces(image_rgb)
    for face in faces:
        x,y, width, height = face['box']
        face_crop = image[y:y+height, x: x + width]
        face_crop = cv2.resize(face_crop, (160, 160))
        faces_data.append(face_crop)
        labels_data.append(label)
print(f"Tổng số gương mặt: {len(faces_data)}")

2025-08-17 03:33:10.642374: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-17 03:33:10.643651: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-08-17 03:33:10.695860: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-08-17 03:33:12.098605: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To tur

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━

In [38]:
cv2.imshow("Sample Face", faces_data[130])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
faces_data[0].shape

(160, 160, 3)

In [4]:
faces_data[0].flatten()

array([ 37,  26,  28, ..., 244, 240, 255], dtype=uint8)

In [5]:
np.array(faces_data[0].flatten())

array([ 37,  26,  28, ..., 244, 240, 255], dtype=uint8)

In [27]:
import csv
# Luu anh bang file csv
output_path = "/home/nguyenngocduong/Desktop/face_recognition_project/Face_Detection/faces_data.csv"
if not os.path.exists(output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, 'w') as f:
    writer = csv.writer(f)
    writer.writerow(['label', 'image'])
    for label, face in zip(labels_data, faces_data):
        face_flat = face.flatten()
        writer.writerow([label, np.array(face_flat)])

In [6]:
import tensorflow as tf
from tensorflow.keras.applications import InceptionResNetV2
from tensorflow.keras.applications.inception_resnet_v2 import preprocess_input
from tensorflow.keras.preprocessing import image
import numpy as np

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.20.0


In [9]:
model = InceptionResNetV2(weights="imagenet", include_top=False, pooling='avg')
img = image.load_img("data/Dat/pic12.jpg", target_size=(299, 299))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)  # Chuẩn hóa theo style Inception
embedding = model.predict(x)
print("Embedding shape:", embedding.shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
Embedding shape: (1, 1536)


In [10]:
embedding

array([[0.10648407, 0.13149378, 0.7440245 , ..., 0.6585734 , 0.20506865,
        0.9902686 ]], dtype=float32)

In [35]:
from src.extract_embedding import *
embeddings = extract_embedding(faces_data, model)

In [36]:
import csv
#Luu embedding vao file csv
output_embedding_path = "/home/nguyenngocduong/Desktop/face_recognition_project/face_embeddings.csv"
if not os.path.exists(output_embedding_path):
    os.makedirs(os.path.dirname(output_embedding_path), exist_ok=True)
with open(output_embedding_path, 'w') as f:
    writer = csv.writer(f)
    writer.writerow(['label'] + [f'feature_{i}' for i in range(embeddings.shape[1])])
    for label, embedding in zip(labels_data, embeddings):
        writer.writerow([label] + embedding.tolist())

In [37]:
embeddings.shape

(165, 1, 1536)

In [38]:
for i, emb in enumerate(embeddings):
    print(f"Embedding {i} shape: {emb.shape}")

Embedding 0 shape: (1, 1536)
Embedding 1 shape: (1, 1536)
Embedding 2 shape: (1, 1536)
Embedding 3 shape: (1, 1536)
Embedding 4 shape: (1, 1536)
Embedding 5 shape: (1, 1536)
Embedding 6 shape: (1, 1536)
Embedding 7 shape: (1, 1536)
Embedding 8 shape: (1, 1536)
Embedding 9 shape: (1, 1536)
Embedding 10 shape: (1, 1536)
Embedding 11 shape: (1, 1536)
Embedding 12 shape: (1, 1536)
Embedding 13 shape: (1, 1536)
Embedding 14 shape: (1, 1536)
Embedding 15 shape: (1, 1536)
Embedding 16 shape: (1, 1536)
Embedding 17 shape: (1, 1536)
Embedding 18 shape: (1, 1536)
Embedding 19 shape: (1, 1536)
Embedding 20 shape: (1, 1536)
Embedding 21 shape: (1, 1536)
Embedding 22 shape: (1, 1536)
Embedding 23 shape: (1, 1536)
Embedding 24 shape: (1, 1536)
Embedding 25 shape: (1, 1536)
Embedding 26 shape: (1, 1536)
Embedding 27 shape: (1, 1536)
Embedding 28 shape: (1, 1536)
Embedding 29 shape: (1, 1536)
Embedding 30 shape: (1, 1536)
Embedding 31 shape: (1, 1536)
Embedding 32 shape: (1, 1536)
Embedding 33 shape: 